class ResolvingError(Exception):
    pass


class ArgumentValidationError(Exception):
    pass
